use wasm_bindgen::prelude::*;
use serde::{Deserialize, Serialize};

// ── Input type ────────────────────────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FinancialData {
    report_id: String,
    company: String,
    period: String,
    revenue: u64,
    profit: u64,
}

// ── Output types ──────────────────────────────────────────────────────

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NormalizedFinancialData {
    report_id: String,
    company: String,
    period: String,
    revenue: String,
    profit: String,
}

// ── Field element conversion ──────────────────────────────────────────

/// Convert a string to a deterministic field element representation.
/// Each character's UTF-8 code point is packed into a hex string,
/// then the result is used as a BigInt-compatible field element.
fn string_to_field_element(s: &str) -> String {
    let hex: String = s.bytes()
        .map(|b| format!("{:02x}", b))
        .collect();
    format!("0x{}", hex)
}

/// Convert a u64 integer to a field element representation.
fn u64_to_field_element(v: u64) -> String {
    v.to_string()
}

// ── Core normalization ────────────────────────────────────────────────

fn normalize_financial(input: &FinancialData) -> NormalizedFinancialData {
    NormalizedFinancialData {
        report_id: string_to_field_element(&input.report_id),
        company: string_to_field_element(&input.company),
        period: string_to_field_element(&input.period),
        revenue: u64_to_field_element(input.revenue),
        profit: u64_to_field_element(input.profit),
    }
}

// ── Error types ───────────────────────────────────────────────────────

#[derive(Serialize)]
#[serde(tag = "error")]
enum NormalizeError {
    StringifyFailed,
    ParseFailed(String),
    SerializeFailed(String),
}

impl NormalizeError {
    fn to_js_value(&self) -> JsValue {
        let json = serde_json::to_string(self).unwrap_or_else(|_| {
            r#"{"error":"SerializeFailed"}"#.to_string()
        });
        JsValue::from_str(&json)
    }
}

// ── WASM exports ──────────────────────────────────────────────────────

/// Normalize financial JSON data into field element representations.
/// The normalizer does NOT compute docHash — that is generated by the
/// Lemma oracle during document registration.
#[wasm_bindgen]
pub fn normalize(input: JsValue) -> JsValue {
    let input_str = match js_sys::JSON::stringify(&input) {
        Ok(s) => s.as_string().unwrap_or_else(|| String::from("{}")),
        Err(_) => {
            return NormalizeError::StringifyFailed.to_js_value();
        }
    };

    let data: FinancialData = match serde_json::from_str(&input_str) {
        Ok(d) => d,
        Err(e) => {
            return NormalizeError::ParseFailed(e.to_string()).to_js_value();
        }
    };

    let normalized = normalize_financial(&data);

    let output_json = match serde_json::to_string(&normalized) {
        Ok(s) => s,
        Err(e) => {
            return NormalizeError::SerializeFailed(e.to_string()).to_js_value();
        }
    };

    JsValue::from_str(&output_json)
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_q1_2026_report() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: 1250000000,
            profit: 340000000,
        };
        let output = normalize_financial(&input);

        assert_eq!(output.report_id, string_to_field_element("2026q1"));
        assert_eq!(output.company, string_to_field_element("Example Corp"));
        assert_eq!(output.period, string_to_field_element("2026-Q1"));
        assert_eq!(output.revenue, "1250000000");
        assert_eq!(output.profit, "340000000");
    }

    #[test]
    fn deterministic_output() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: 1250000000,
            profit: 340000000,
        };
        let output1 = normalize_financial(&input);
        let output2 = normalize_financial(&input);

        let json1 = serde_json::to_string(&output1).unwrap();
        let json2 = serde_json::to_string(&output2).unwrap();

        assert_eq!(json1, json2, "Normalized output must be deterministic");
    }

    #[test]
    fn string_to_field_element_produces_hex() {
        let fe = string_to_field_element("2026q1");
        assert!(fe.starts_with("0x"));
        assert_eq!(fe, "0x323032367131");
    }

    #[test]
    fn u64_to_field_element_uses_decimal() {
        assert_eq!(u64_to_field_element(1250000000), "1250000000");
        assert_eq!(u64_to_field_element(0), "0");
    }

    #[test]
    fn revenue_field_conversion() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: 1250000000,
            profit: 340000000,
        };
        let output = normalize_financial(&input);
        assert_eq!(output.revenue, "1250000000");
    }
}
