use wasm_bindgen::prelude::*;
use serde::{Deserialize, Serialize};

// ── Input type ────────────────────────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FinancialData {
    report_id: String,
    company: String,
    period: String,
    revenue: String,
    profit: String,
}

// ── Output types ──────────────────────────────────────────────────────

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NormalizedFinancialData {
    report_id: String,
    company: String,
    period: String,
    revenue: String,
    profit: String,
}

// ── Field element conversion ──────────────────────────────────────────

/// Convert a string to a deterministic field element representation.
/// Each character's UTF-8 code point is packed into a hex string,
/// then the result is used as a BigInt-compatible field element.
fn string_to_field_element(s: &str) -> String {
    let hex: String = s.bytes()
        .map(|b| format!("{:02x}", b))
        .collect();
    format!("0x{}", hex)
}

// ── Core normalization ────────────────────────────────────────────────

fn normalize_financial(input: &FinancialData) -> NormalizedFinancialData {
    NormalizedFinancialData {
        report_id: string_to_field_element(&input.report_id),
        company: string_to_field_element(&input.company),
        period: string_to_field_element(&input.period),
        revenue: string_to_field_element(&input.revenue),
        profit: string_to_field_element(&input.profit),
    }
}

// ── Error types ───────────────────────────────────────────────────────

#[derive(Serialize)]
#[serde(tag = "error")]
enum NormalizeError {
    ParseFailed(String),
    SerializeFailed(String),
}

// ── WASM exports ──────────────────────────────────────────────────────

/// Normalize financial JSON data into field element representations.
/// The normalizer does NOT compute docHash — that is generated by the
/// Lemma oracle during document registration.
#[wasm_bindgen]
pub fn normalize(raw_json: &str) -> String {
    let data: FinancialData = match serde_json::from_str(raw_json) {
        Ok(d) => d,
        Err(e) => {
            let err = NormalizeError::ParseFailed(e.to_string());
            return serde_json::to_string(&err).unwrap_or_else(|_| r#"{"error":"SerializeFailed"}"#.to_string());
        }
    };

    let normalized = normalize_financial(&data);

    match serde_json::to_string(&normalized) {
        Ok(s) => s,
        Err(e) => {
            let err = NormalizeError::SerializeFailed(e.to_string());
            serde_json::to_string(&err).unwrap_or_else(|_| r#"{"error":"SerializeFailed"}"#.to_string())
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_q1_2026_report() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: "$1.25B".to_string(),
            profit: "$340M".to_string(),
        };
        let output = normalize_financial(&input);

        assert_eq!(output.report_id, string_to_field_element("2026q1"));
        assert_eq!(output.company, string_to_field_element("Example Corp"));
        assert_eq!(output.period, string_to_field_element("2026-Q1"));
        assert_eq!(output.revenue, string_to_field_element("$1.25B"));
        assert_eq!(output.profit, string_to_field_element("$340M"));
    }

    #[test]
    fn deterministic_output() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: "$1.25B".to_string(),
            profit: "$340M".to_string(),
        };
        let output1 = normalize_financial(&input);
        let output2 = normalize_financial(&input);

        let json1 = serde_json::to_string(&output1).unwrap();
        let json2 = serde_json::to_string(&output2).unwrap();

        assert_eq!(json1, json2, "Normalized output must be deterministic");
    }

    #[test]
    fn string_to_field_element_produces_hex() {
        let fe = string_to_field_element("2026q1");
        assert!(fe.starts_with("0x"));
        assert_eq!(fe, "0x323032367131");
    }

    #[test]
    fn revenue_field_conversion() {
        let input = FinancialData {
            report_id: "2026q1".to_string(),
            company: "Example Corp".to_string(),
            period: "2026-Q1".to_string(),
            revenue: "$1.25B".to_string(),
            profit: "$340M".to_string(),
        };
        let output = normalize_financial(&input);
        assert_eq!(output.revenue, string_to_field_element("$1.25B"));
    }
}
